[zh-tw]
  title = "免費開源TRPG中文化團隊"
  languageName = "繁體中文"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/zh-tw"

[ko]
  title = "Hugo Zzo Theme"
  languageName = "한국어"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/ko"
