[[main]]
  identifier = "about"
  name = "關於我們"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "目錄"
  url = "archive"
  weight = 2
    
[[main]]
  identifier = "posts"
  name = "翻譯規則"
  url = "posts"
  weight = 4